### ISSUE TITLE
URLs in edited messages are not clickable

### ISSUE THREAD

**Issue by dorian-marchal** [g3rv4/Refined#18]
Steps to reproduce:
- Post a message with a URL (e.g. https://chris.beams.io/posts/git-commit/).
- The link is clickable.
- Edit this messages.

Observed result:
- The link is not clickable anymore.

Expected result:
- The link still can be clicked.

**Comment by g3rv4** [comment]
Hi there! I'm unable to get a repro for this one... check how it works on my browser:

![](https://gmc.uy/linkEdit.gif)

do you have any errors on the console? can you see anything I'm doing different from you?

**Comment by g3rv4** [comment]
ooohhh, I see... you meant _not_ using markdown for the link... I got a repro, I'll work on it when I have a sec (feel free to work on it if you'd like... it's def an issue [in these lines](https://github.com/g3rv4/Taut/blob/3f1085c3575403b8c5e2059c430c2548e6b4afdb/src/plugins/markdownLinks.ts#L18-L20))

**Comment by g3rv4** [comment]
Thanks for reporting this! unsurprisingly, [the fix was on a totally different place](https://github.com/g3rv4/Taut/commit/595a469066e01ca77fab7407ad51331b53feee05) (and... it was using an undocumented value on that API call :sigh:).

2.1.1 is available on Chrome with the fix (and I've submitted it to Firefox and Opera as well).

Thanks again!

**Comment by dorian-marchal** [comment]
Oh, you're fast! Thanks :ok_hand:
