### ISSUE TITLE
Positioning Reactions

### ISSUE THREAD

**Issue by tommygebru** [g3rv4/Refined#31]
Really enjoying personalizing my slack workspaces 👌 

Can we make reactions become inline with the Slack user's name + status/timestamp?

Currently reactions are layered above the messages themselves so its hard to read, and sometimes there may even be reactions layered above emojis 😉

**Comment by g3rv4** [comment]
I don’t see why we couldn’t :) would you be able to code it? you can see the current plugin for inspiration, but I guess you’d need to change some elements’ parents in the DOM.

If you want to bounce ideas or put a PR together I’d be happy to chat and take a look.

**Comment by g3rv4** [comment]
I took this for a spin... and the problem is that the user's name + status/timestamp don't always show for all the messages. In particular, when one user posts several messages, there's only one user name and timestamp... but people can react to the messages individually.

Check this screenshot for an example:

![example](https://gervas.io/reactionPositions.png)

So I don't think we can implement this in a way that makes sense.
